#!/bin/sh

NUM="${2:-5}"

case "$1" in
  toggle) pulsemixer --toggle-mute ;;
  mute) pulsemixer --mute ;;
  up) pulsemixer --change-volume +"$NUM" ;;
  down) pulsemixer --change-volume -"$NUM" ;;
esac>/dev/null
