#!/bin/sh

ffmpeg -y -f pulseaudio -i default -acodec pcm_s16le -ac 1 -ar 44100 -t 4 -f wav ~/cache/audio.wav >/dev/null 2>&1 vosk-transcriber -m ~/.local/share/kdenlive/speechmodels/vosk-model-small-en-us-0.15 -i ~/.cache/audio.wav -o ~/.cache/transcript.txt >/dev/null 2>$&1
cat ~/.cache/transcript.txt
